# SPDX-License-Identifier: GPL-2.0-or-later
#
# Makefile for smbdirect support
#

obj-$(CONFIG_SMB_COMMON_SMBDIRECT) += smbdirect.o

smbdirect-y := \
	smbdirect_connection.o	\
	smbdirect_mr.o		\
	smbdirect_rw.o		\
	smbdirect_debug.o	\
	smbdirect_connect.o	\
	smbdirect_accept.o	\
	smbdirect_main.o
